sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=resources-17062-ubuntu-1604
  - INSTANCE=network-ubuntu-1604
  - INSTANCE=volume-ubuntu-1604
  # - INSTANCE=smoke-amazonlinux
  - INSTANCE=smoke-debian-7
  - INSTANCE=smoke-debian-8
  - INSTANCE=smoke-debian-9
  - INSTANCE=smoke-centos-7
  - INSTANCE=smoke-fedora-25
  - INSTANCE=smoke-ubuntu-1404
  - INSTANCE=smoke-ubuntu-1604
  - INSTANCE=smoke-ubuntu-1704

# Ensure we make ChefDK's Ruby the default
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
