#
# This file is structured to be consumed by both humans and computers.
# It is a TOML document containing Markdown
#
[Preamble]
  title = "Maintainers"
  text = """

This file lists how this cookbook project is maintained. When making changes to the system, this file tells you who needs to review your patch - you need a review from an existing maintainer for the cookbook to provide a :+1: on your pull request. Additionally, you need to not receive a veto from a Lieutenant or the Project Lead.

Check out [How Cookbooks are Maintained](https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD) for details on the process and how to become a maintainer or the project lead.
"""

[Org]
  [Org.Components]
    [Org.Components.Core]
      title = "Project Maintainer"

      lieutenant = 'someara'

      maintainers = [
        'sigje',
        'someara',
        'tas50',
        'thommay',
        'scalp42',
        'chasebolt',
        'bflad',
        'tduffield'
      ]

[people]
  [people.sigje]
    name = "Jennifer Davis"
    github = "sigje"

  [people.someara]
    name = "Sean OMeara"
    github = "someara"

  [people.tas50]
    name = "Tim Smith"
    github = "tas50"

  [people.thommay]
    name = "Thom May"
    github = "thommay"

  [people.scalp42]
    name = "Anthony Scalisi"
    github = "scalp42"

  [people.chasebolt]
    name = "Chase Bolt"
    github = "chasebolt"

  [people.bflad]
    name = "Brian Flad"
    github = "bflad"

  [people.tduffield]
    name = "Tom Duffield"
    github = "tduffield"
