---
name: md-links

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  md-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1.0.13
        with:
          use-verbose-mode: "yes"
          folder-path: "documentation"
